# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.5

pipelines:
  deafults:
    - step:
      script:
        - uname -a
        - gcc --version
        - apt-get update -qq
        - apt-get install cmake -y
        - cmake --version
        - mkdir build
        - cd build
        - cmake .. -DUNITTEST=1
        - make
        - ./Classes/test/unitest_exec
  pull-requests:
    '**':
      - step:
          script:
            # Print the Linux version.
            - uname -a
            # Print the gcc version.
            - gcc --version
            #  Install a CMake 3.0.2 version.
            - apt-get update -qq
            - apt-get install cmake -y
            # Print the CMake version.
            - cmake --version
            - mkdir build
            - cd build
            # Call the CMake.
            - cmake .. -DUNITTEST=1
            # Build the project.
            - make
            # Run the tests
            - ./Classes/test/unittest_exec