# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.5

pipelines:
  default:
    - step:
        script:
          - uname -a
          - apt-get update -qq
          - apt install build-essential
          - apt-get install cmake -y
          - cmake --version
          - mkdir -p build
          - cd build
          - cmake .. -DUNITTEST=ON -DCLANGTIDY=OFF -DSANITIZER=address
          - make unittest_exec
          - ./Classes/game_logic/test/unittest_exec
          - cmake .. -DUNITTEST=ON -DCLANGTIDY=OFF -DSANITIZER=thread
          - make unittest_exec
          - ./Classes/game_logic/test/unittest_exec
          - cmake .. -DUNITTEST=ON -DCLANGTIDY=OFF -DSANITIZER=undefined
          - make unittest_exec
          - ./Classes/game_logic/test/unittest_exec
